/**
 * Constantes relacionadas con artículos:
 * - Estados, marcas, colores, materiales
 * - Categorías y tipos de productos
 * - Filtros de precio y categorías
 */
import type {
  LabelsByLanguage,
  CategoryFilter,
  ArticleSecondChanceStatus,
  Lang,
  OfferOption,
} from '@/types/types';

export const ARTICLE_STATE_LABELS: LabelsByLanguage = {
  es: {
    NEVER_WORN_WITH_TAG: 'Nunca Usado con Etiqueta',
    NEVER_WORN: 'Nunca Usado',
    VERY_GOOD_CONDITION: 'Muy Buen Estado',
    GOOD_CONDITION: 'Buen Estado',
    FAIR_CONDITION: 'Estado Aceptable',
  },
  en: {
    NEVER_WORN_WITH_TAG: 'Never Worn with Tag',
    NEVER_WORN: 'Never Worn',
    VERY_GOOD_CONDITION: 'Very Good Condition',
    GOOD_CONDITION: 'Good Condition',
    FAIR_CONDITION: 'Fair Condition',
  },
};

export const ARTICLE_STATE = {
  es: [
    { value: 'NEVER_WORN_WITH_TAG', label: 'Nunca Usado con Etiqueta' },
    { value: 'NEVER_WORN', label: 'Nunca Usado' },
    { value: 'VERY_GOOD_CONDITION', label: 'Muy Buen Estado' },
    { value: 'GOOD_CONDITION', label: 'Buen Estado' },
    { value: 'FAIR_CONDITION', label: 'Estado Aceptable' },
  ],
  en: [
    { value: 'NEVER_WORN_WITH_TAG', label: 'Never Worn with Tag' },
    { value: 'NEVER_WORN', label: 'Never Worn' },
    { value: 'VERY_GOOD_CONDITION', label: 'Very Good Condition' },
    { value: 'GOOD_CONDITION', label: 'Good Condition' },
    { value: 'FAIR_CONDITION', label: 'Fair Condition' },
  ],
};

export const ARTICLE_STATUS_LABELS = {
  es: {
    NOT_PUBLISHED: 'No publicado',
    NEED_CHANGES: 'Necesita cambios',
    CHANGES_MADE: 'Cambios realizados',
    APPROVED: 'Aprobado',
    PUBLISHED: 'Publicado',
  },
  en: {
    NOT_PUBLISHED: 'Not published',
    NEED_CHANGES: 'Needs changes',
    CHANGES_MADE: 'Changes made',
    APPROVED: 'Approved',
    PUBLISHED: 'Published',
  },
};

export enum ArticleStatus {
  NOT_PUBLISHED = 'NOT_PUBLISHED',
  NEED_CHANGES = 'NEED_CHANGES',
  CHANGES_MADE = 'CHANGES_MADE',
  APPROVED = 'APPROVED',
  PUBLISHED = 'PUBLISHED',
}

export const ARTICLE_STATE_DESCRIPTION: LabelsByLanguage = {
  es: {
    NEVER_WORN_WITH_TAG:
      'Como nuevo, con la etiqueta original aún adherida y sin signos de uso, daño o modificaciones.',
    NEVER_WORN:
      'En estado impecable, sin señales de desgaste, daños o alteraciones.',
    VERY_GOOD_CONDITION:
      'Ligeramente usado, bien conservado, sin rasgaduras, bolitas o decoloración.',
    GOOD_CONDITION:
      'Usado moderadamente, aún en buen estado pero puede mostrar un ligero desgaste del tejido o pequeñas imperfecciones.',
    FAIR_CONDITION:
      'Muy usado, con defectos visibles y signos evidentes de uso frecuente.',
  },
  en: {
    NEVER_WORN_WITH_TAG:
      'Like new, with the original tag still attached, and no signs of wear, damage, or modifications.',
    NEVER_WORN:
      'Flawless condition, showing no signs of wear, damage, or alterations.',
    VERY_GOOD_CONDITION:
      'Gently worn, carefully preserved with no rips, fuzzing, or fading.',
    GOOD_CONDITION:
      'Moderately used, still in good shape but may show minor fabric wear or small imperfections.',
    FAIR_CONDITION:
      'Heavily worn, with noticeable defects and signs of frequent use.',
  },
};

export const ARTICLE_SMELL_LABELS: LabelsByLanguage = {
  es: {
    TOBACCO: 'Tabaco',
    PERFUME: 'Perfume',
    HUMIDITY: 'Humedad',
    NO_SMELL: 'Sin olor',
    OTHER: 'Otro',
  },
  en: {
    TOBACCO: 'Tobacco',
    PERFUME: 'Perfume',
    HUMIDITY: 'Humidity',
    NO_SMELL: 'No smell',
    OTHER: 'Other',
  },
};

export const ARTICLE_BRANDS = [
  { value: 'NON_SIGNE', label: 'non signé' },
  { value: 'A_LANGE_SOHNE', label: 'A. Lange & Söhne' },
  { value: 'AUDEMARS_PIGUET', label: 'Audemars Piguet' },
  { value: 'BALENCIAGA', label: 'Balenciaga' },
  { value: 'BALMAIN', label: 'Balmain' },
  { value: 'BAUME_MERCIER', label: 'Baume & Mercier' },
  { value: 'BELL_ROSS', label: 'Bell & Ross' },
  { value: 'BLANCPAIN', label: 'Blancpain' },
  { value: 'BOVET', label: 'Bovet' },
  { value: 'BOUCHERON', label: 'Boucheron' },
  { value: 'BOTTEGA_VENETA', label: 'Bottega Veneta' },
  { value: 'BREGUET', label: 'Breguet' },
  { value: 'BREITLING', label: 'Breitling' },
  { value: 'BUCCELLATI', label: 'Buccellati' },
  { value: 'BULGARI', label: 'Bulgari' },
  { value: 'BURBERRY', label: 'Burberry' },
  { value: 'CARTIER', label: 'Cartier' },
  { value: 'CELINE', label: 'Celine' },
  { value: 'CHANEL', label: 'Chanel' },
  { value: 'CHAUMET', label: 'Chaumet' },
  { value: 'CHLOE', label: 'Chloe' },
  { value: 'CHOPARD', label: 'Chopard' },
  { value: 'CHRISTIAN_DIOR', label: 'Christian Dior' },
  { value: 'CHRISTIAN_LOUBOUTIN', label: 'Christian Louboutin' },
  { value: 'CORUM', label: 'Corum' },
  { value: 'DAMIANI', label: 'Damiani' },
  { value: 'DAVID_YURMAN', label: 'David Yurman' },
  { value: 'DE_BEERS', label: 'De Beers' },
  { value: 'DIOR_HOMME', label: 'Dior Homme' },
  { value: 'DODO', label: 'Dodo' },
  { value: 'DOLCE_GABBANA', label: 'Dolce Gabbana' },
  { value: 'D_G', label: 'D&G' },
  { value: 'FABERGE', label: 'Fabergé' },
  { value: 'FENDI', label: 'Fendi' },
  { value: 'FERRAGAMO', label: 'Ferragamo' },
  { value: 'FP_JOURNE', label: 'F.P. Journe' },
  { value: 'FRANCK_MULLER', label: 'Franck Muller' },
  { value: 'GARRARD', label: 'Garrard' },
  { value: 'GIVENCHY', label: 'Givenchy' },
  { value: 'GLASHUTTE_ORIGINAL', label: 'Glashütte Original' },
  { value: 'GOYARD', label: 'Goyard' },
  { value: 'GRAND_SEIKO', label: 'Grand Seiko' },
  { value: 'GRAFF', label: 'Graff' },
  { value: 'GUCCI', label: 'Gucci' },
  { value: 'HARRY_WINSTON', label: 'Harry Winston' },
  { value: 'HERMES', label: 'Hermès' },
  { value: 'HUBLOT', label: 'Hublot' },
  { value: 'IWC_SCHAFFHAUSEN', label: 'IWC Schaffhausen' },
  { value: 'JACQUEMUS', label: 'Jacquemus' },
  { value: 'JAEGER_LECOULTRE', label: 'Jaeger-LeCoultre' },
  { value: 'KWIAT', label: 'Kwiat' },
  { value: 'LONGINES', label: 'Longines' },
  { value: 'LOEWE', label: 'Loewe' },
  { value: 'LORENZ_BAUMER', label: 'Lorenz Bäumer' },
  { value: 'LOUIS_VUITTON', label: 'Louis Vuitton' },
  { value: 'MAURICE_LACROIX', label: 'Maurice Lacroix' },
  { value: 'MESSIKA', label: 'Messika' },
  { value: 'MIKIMOTO', label: 'Mikimoto' },
  { value: 'MIU_MIU', label: 'Miu Miu' },
  { value: 'MONTBLANC', label: 'Montblanc' },
  { value: 'MOUSSAIEFF', label: 'Moussaieff' },
  { value: 'NOOR_FARES', label: 'Noor Fares' },
  { value: 'OMEGA', label: 'Omega' },
  { value: 'OLE_LYNGGAARD_COPENHAGEN', label: 'Ole Lynggaard Copenhagen' },
  { value: 'PANERAI', label: 'Panerai' },
  { value: 'PARMIGIANI_FLEURIER', label: 'Parmigiani Fleurier' },
  { value: 'PATEK_PHILIPPE', label: 'Patek Philippe' },
  { value: 'PIAGET', label: 'Piaget' },
  { value: 'POMELLATO', label: 'Pomellato' },
  { value: 'PRADA', label: 'Prada' },
  { value: 'RICHARD_MILLE', label: 'Richard Mille' },
  { value: 'ROBERTO_COIN', label: 'Roberto Coin' },
  { value: 'ROLEX', label: 'Rolex' },
  { value: 'SAINT_LAURENT', label: 'Saint Laurent' },
  { value: 'SHAUN_LEANE', label: 'Shaun Leane' },
  { value: 'STEPHEN_WEBSTER', label: 'Stephen Webster' },
  { value: 'TAG_HEUER', label: 'TAG Heuer' },
  { value: 'TAFFIN', label: 'Taffin' },
  { value: 'TIFFANY_CO', label: 'Tiffany & Co' },
  { value: 'TUDOR', label: 'Tudor' },
  { value: 'ULYSSE_NARDIN', label: 'Ulysse Nardin' },
  { value: 'VACHERON_CONSTANTIN', label: 'Vacheron Constantin' },
  { value: 'VALENTINO_GARAVANI', label: 'Valentino Garavani' },
  { value: 'VAN_CLEEF_ARPELS', label: 'Van Cleef & Arpels' },
  { value: 'VERSACE', label: 'Versace' },
  { value: 'ZENITH', label: 'Zenith' },
];

export const ARTICLE_BRANDS_LABELS = {
  NON_SIGNE: 'non signé',
  A_LANGE_SOHNE: 'A. Lange & Söhne',
  AUDEMARS_PIGUET: 'Audemars Piguet',
  BALENCIAGA: 'Balenciaga',
  BALMAIN: 'Balmain',
  BAUME_MERCIER: 'Baume & Mercier',
  BELL_ROSS: 'Bell & Ross',
  BLANCPAIN: 'Blancpain',
  BOVET: 'Bovet',
  BOUCHERON: 'Boucheron',
  BOTTEGA_VENETA: 'Bottega Veneta',
  BREGUET: 'Breguet',
  BREITLING: 'Breitling',
  BUCCELLATI: 'Buccellati',
  BULGARI: 'Bulgari',
  BURBERRY: 'Burberry',
  CARTIER: 'Cartier',
  CELINE: 'Celine',
  CHANEL: 'Chanel',
  CHAUMET: 'Chaumet',
  CHLOE: 'Chloe',
  CHOPARD: 'Chopard',
  CHRISTIAN_DIOR: 'Christian Dior',
  CHRISTIAN_LOUBOUTIN: 'Christian Louboutin',
  CORUM: 'Corum',
  DAMIANI: 'Damiani',
  DAVID_YURMAN: 'David Yurman',
  DE_BEERS: 'De Beers',
  DIOR_HOMME: 'Dior Homme',
  DODO: 'Dodo',
  DOLCE_GABBANA: 'Dolce Gabbana',
  D_G: 'D&G',
  FABERGE: 'Fabergé',
  FENDI: 'Fendi',
  FERRAGAMO: 'Ferragamo',
  FP_JOURNE: 'F.P. Journe',
  FRANCK_MULLER: 'Franck Muller',
  GARRARD: 'Garrard',
  GIVENCHY: 'Givenchy',
  GLASHUTTE_ORIGINAL: 'Glashütte Original',
  GOYARD: 'Goyard',
  GRAND_SEIKO: 'Grand Seiko',
  GRAFF: 'Graff',
  GUCCI: 'Gucci',
  HARRY_WINSTON: 'Harry Winston',
  HERMES: 'Hermès',
  HUBLOT: 'Hublot',
  IWC_SCHAFFHAUSEN: 'IWC Schaffhausen',
  JACQUEMUS: 'Jacquemus',
  JAEGER_LECOULTRE: 'Jaeger-LeCoultre',
  KWIAT: 'Kwiat',
  LONGINES: 'Longines',
  LOEWE: 'Loewe',
  LORENZ_BAUMER: 'Lorenz Bäumer',
  LOUIS_VUITTON: 'Louis Vuitton',
  MAURICE_LACROIX: 'Maurice Lacroix',
  MESSIKA: 'Messika',
  MIKIMOTO: 'Mikimoto',
  MIU_MIU: 'Miu Miu',
  MONTBLANC: 'Montblanc',
  MOUSSAIEFF: 'Moussaieff',
  NOOR_FARES: 'Noor Fares',
  OMEGA: 'Omega',
  OLE_LYNGGAARD_COPENHAGEN: 'Ole Lynggaard Copenhagen',
  PANERAI: 'Panerai',
  PARMIGIANI_FLEURIER: 'Parmigiani Fleurier',
  PATEK_PHILIPPE: 'Patek Philippe',
  PIAGET: 'Piaget',
  POMELLATO: 'Pomellato',
  PRADA: 'Prada',
  RICHARD_MILLE: 'Richard Mille',
  ROBERTO_COIN: 'Roberto Coin',
  ROLEX: 'Rolex',
  SAINT_LAURENT: 'Saint Laurent',
  SHAUN_LEANE: 'Shaun Leane',
  STEPHEN_WEBSTER: 'Stephen Webster',
  TAG_HEUER: 'TAG Heuer',
  TAFFIN: 'Taffin',
  TIFFANY_CO: 'Tiffany & Co',
  TUDOR: 'Tudor',
  ULYSSE_NARDIN: 'Ulysse Nardin',
  VACHERON_CONSTANTIN: 'Vacheron Constantin',
  VALENTINO_GARAVANI: 'Valentino Garavani',
  VAN_CLEEF_ARPELS: 'Van Cleef & Arpels',
  VERSACE: 'Versace',
  ZENITH: 'Zenith',
};

export const ARTICLE_COLORS = {
  es: [
    { value: 'MULTICOLOUR', label: 'Multicolor' },
    { value: 'OTHER', label: 'Otro' },
    { value: 'BEIGE', label: 'Beige' },
    { value: 'BLACK', label: 'Negro' },
    { value: 'BLUE', label: 'Azul' },
    { value: 'BROWN', label: 'Marrón' },
    { value: 'BURGUNDY', label: 'Burdeos' },
    { value: 'CAMEL', label: 'Camel' },
    { value: 'CHARCOAL', label: 'Carbón' },
    { value: 'ECRU', label: 'Crudo' },
    { value: 'GOLD', label: 'Dorado' },
    { value: 'GREEN', label: 'Verde' },
    { value: 'GREY', label: 'Gris' },
    { value: 'KHAKI', label: 'Caqui' },
    { value: 'METALLIC', label: 'Metálico' },
    { value: 'NAVY', label: 'Azul Marino' },
    { value: 'ORANGE', label: 'Naranja' },
    { value: 'PINK', label: 'Rosa' },
    { value: 'PURPLE', label: 'Morado' },
    { value: 'RED', label: 'Rojo' },
    { value: 'SILVER', label: 'Plateado' },
    { value: 'TURQUOISE', label: 'Turquesa' },
    { value: 'WHITE', label: 'Blanco' },
    { value: 'YELLOW', label: 'Amarillo' },
  ],
  en: [
    { value: 'MULTICOLOUR', label: 'Multicolour' },
    { value: 'OTHER', label: 'Other' },
    { value: 'BEIGE', label: 'Beige' },
    { value: 'BLACK', label: 'Black' },
    { value: 'BLUE', label: 'Blue' },
    { value: 'BROWN', label: 'Brown' },
    { value: 'BURGUNDY', label: 'Burgundy' },
    { value: 'CAMEL', label: 'Camel' },
    { value: 'CHARCOAL', label: 'Charcoal' },
    { value: 'ECRU', label: 'Ecru' },
    { value: 'GOLD', label: 'Gold' },
    { value: 'GREEN', label: 'Green' },
    { value: 'GREY', label: 'Grey' },
    { value: 'KHAKI', label: 'Khaki' },
    { value: 'METALLIC', label: 'Metallic' },
    { value: 'NAVY', label: 'Navy' },
    { value: 'ORANGE', label: 'Orange' },
    { value: 'PINK', label: 'Pink' },
    { value: 'PURPLE', label: 'Purple' },
    { value: 'RED', label: 'Red' },
    { value: 'SILVER', label: 'Silver' },
    { value: 'TURQUOISE', label: 'Turquoise' },
    { value: 'WHITE', label: 'White' },
    { value: 'YELLOW', label: 'Yellow' },
  ],
};

export const ARTICLE_COLORS_LABELS: LabelsByLanguage = {
  es: {
    MULTICOLOUR: 'Multicolor',
    OTHER: 'Otro',
    BEIGE: 'Beige',
    BLACK: 'Negro',
    BLUE: 'Azul',
    BROWN: 'Marrón',
    BURGUNDY: 'Burdeos',
    CAMEL: 'Camel',
    CHARCOAL: 'Carbón',
    ECRU: 'Crudo',
    GOLD: 'Dorado',
    GREEN: 'Verde',
    GREY: 'Gris',
    KHAKI: 'Caqui',
    METALLIC: 'Metálico',
    NAVY: 'Azul Marino',
    ORANGE: 'Naranja',
    PINK: 'Rosa',
    PURPLE: 'Morado',
    RED: 'Rojo',
    SILVER: 'Plateado',
    TURQUOISE: 'Turquesa',
    WHITE: 'Blanco',
    YELLOW: 'Amarillo',
  },
  en: {
    MULTICOLOUR: 'Multicolour',
    OTHER: 'Other',
    BEIGE: 'Beige',
    BLACK: 'Black',
    BLUE: 'Blue',
    BROWN: 'Brown',
    BURGUNDY: 'Burgundy',
    CAMEL: 'Camel',
    CHARCOAL: 'Charcoal',
    ECRU: 'Ecru',
    GOLD: 'Gold',
    GREEN: 'Green',
    GREY: 'Grey',
    KHAKI: 'Khaki',
    METALLIC: 'Metallic',
    NAVY: 'Navy',
    ORANGE: 'Orange',
    PINK: 'Pink',
    PURPLE: 'Purple',
    RED: 'Red',
    SILVER: 'Silver',
    TURQUOISE: 'Turquoise',
    WHITE: 'White',
    YELLOW: 'Yellow',
  },
};

export const ARTICLE_MATERIALS = {
  es: [
    { value: 'CASHMERE', label: 'Cachemira' },
    { value: 'CANVAS', label: 'Lona' },
    { value: 'CLOTH', label: 'Tela' },
    { value: 'COTTON', label: 'Algodón' },
    { value: 'COTTON_ELASTHANE', label: 'Algodón - elastano' },
    { value: 'CRYSTAL', label: 'Cristal' },
    { value: 'DENIM_JEANS', label: 'Denim - Jeans' },
    { value: 'EXOTIC_LEATHERS', label: 'Cueros exóticos' },
    { value: 'FAUX_FUR', label: 'Piel sintética' },
    { value: 'FUR', label: 'Piel' },
    { value: 'GLASS', label: 'Vidrio' },
    { value: 'GLITTER', label: 'Purpurina' },
    { value: 'GOLD_PLATED', label: 'Chapado en oro' },
    { value: 'LACE', label: 'Encaje' },
    { value: 'LEATHER', label: 'Cuero' },
    { value: 'LINEN', label: 'Lino' },
    { value: 'LYCRA', label: 'Lycra' },
    { value: 'METAL', label: 'Metal' },
    { value: 'NOT_SPECIFIED', label: 'No especificado' },
    { value: 'OTHER', label: 'Otro' },
    { value: 'PATENT_LEATHER', label: 'Cuero charolado' },
    { value: 'PEARL', label: 'Perla' },
    { value: 'PINK_GOLD', label: 'Oro rosa' },
    { value: 'PLASTIC', label: 'Plástico' },
    { value: 'POLYAMIDE', label: 'Poliamida' },
    { value: 'POLYESTER', label: 'Poliéster' },
    { value: 'PONY_STYLE_CALFSKIN', label: 'Piel de ternero estilo pony' },
    { value: 'RUBBER', label: 'Caucho' },
    { value: 'SILK', label: 'Seda' },
    { value: 'SILVER', label: 'Plata' },
    { value: 'SILVER_PLATED', label: 'Chapado en plata' },
    { value: 'SPANDEX', label: 'Spandex' },
    { value: 'SPONGE', label: 'Esponja' },
    { value: 'STEEL', label: 'Acero' },
    { value: 'SUEDE', label: 'Gamuza' },
    { value: 'SYNTHETIC', label: 'Sintético' },
    { value: 'TWEED', label: 'Tweed' },
    { value: 'VEGAN_LEATHER', label: 'Cuero vegano' },
    { value: 'VELVET', label: 'Terciopelo' },
    { value: 'VINYL', label: 'Vinilo' },
    { value: 'VISCOSE', label: 'Viscosa' },
    { value: 'WHITE_GOLD', label: 'Oro blanco' },
    { value: 'WICKER', label: 'Mimbre' },
    { value: 'WOOL', label: 'Lana' },
    { value: 'YELLOW_GOLD', label: 'Oro amarillo' },
  ],
  en: [
    { value: 'CASHMERE', label: 'Cashmere' },
    { value: 'CANVAS', label: 'Canvas' },
    { value: 'CLOTH', label: 'Cloth' },
    { value: 'COTTON', label: 'Cotton' },
    { value: 'COTTON_ELASTHANE', label: 'Cotton - Elasthane' },
    { value: 'CRYSTAL', label: 'Crystal' },
    { value: 'DENIM_JEANS', label: 'Denim - Jeans' },
    { value: 'EXOTIC_LEATHERS', label: 'Exotic Leathers' },
    { value: 'FAUX_FUR', label: 'Faux Fur' },
    { value: 'FUR', label: 'Fur' },
    { value: 'GLASS', label: 'Glass' },
    { value: 'GLITTER', label: 'Glitter' },
    { value: 'GOLD_PLATED', label: 'Gold Plated' },
    { value: 'LACE', label: 'Lace' },
    { value: 'LEATHER', label: 'Leather' },
    { value: 'LINEN', label: 'Linen' },
    { value: 'LYCRA', label: 'Lycra' },
    { value: 'METAL', label: 'Metal' },
    { value: 'NOT_SPECIFIED', label: 'Not Specified' },
    { value: 'OTHER', label: 'Other' },
    { value: 'PATENT_LEATHER', label: 'Patent Leather' },
    { value: 'PEARL', label: 'Pearl' },
    { value: 'PINK_GOLD', label: 'Pink Gold' },
    { value: 'PLASTIC', label: 'Plastic' },
    { value: 'POLYAMIDE', label: 'Polyamide' },
    { value: 'POLYESTER', label: 'Polyester' },
    { value: 'PONY_STYLE_CALFSKIN', label: 'Pony-Style Calfskin' },
    { value: 'RUBBER', label: 'Rubber' },
    { value: 'SILK', label: 'Silk' },
    { value: 'SILVER', label: 'Silver' },
    { value: 'SILVER_PLATED', label: 'Silver Plated' },
    { value: 'SPANDEX', label: 'Spandex' },
    { value: 'SPONGE', label: 'Sponge' },
    { value: 'STEEL', label: 'Steel' },
    { value: 'SUEDE', label: 'Suede' },
    { value: 'SYNTHETIC', label: 'Synthetic' },
    { value: 'TWEED', label: 'Tweed' },
    { value: 'VEGAN_LEATHER', label: 'Vegan Leather' },
    { value: 'VELVET', label: 'Velvet' },
    { value: 'VINYL', label: 'Vinyl' },
    { value: 'VISCOSE', label: 'Viscose' },
    { value: 'WHITE_GOLD', label: 'White Gold' },
    { value: 'WICKER', label: 'Wicker' },
    { value: 'WOOL', label: 'Wool' },
    { value: 'YELLOW_GOLD', label: 'Yellow Gold' },
  ],
};

export const ARTICLE_MATERIALS_LABELS: LabelsByLanguage = {
  es: {
    CASHMERE: 'Cachemira',
    CLOTH: 'Tela',
    COTTON: 'Algodón',
    COTTON_ELASTHANE: 'Algodón - elastano',
    CRYSTAL: 'Cristal',
    DENIM_JEANS: 'Denim - Jeans',
    EXOTIC_LEATHERS: 'Cueros exóticos',
    FAUX_FUR: 'Piel sintética',
    FUR: 'Piel',
    GLASS: 'Vidrio',
    GLITTER: 'Purpurina',
    GOLD_PLATED: 'Chapado en oro',
    LACE: 'Encaje',
    LEATHER: 'Cuero',
    LINEN: 'Lino',
    LYCRA: 'Lycra',
    METAL: 'Metal',
    NOT_SPECIFIED: 'No especificado',
    OTHER: 'Otro',
    PATENT_LEATHER: 'Cuero charolado',
    PEARL: 'Perla',
    PINK_GOLD: 'Oro rosa',
    PLASTIC: 'Plástico',
    POLYAMIDE: 'Poliamida',
    POLYESTER: 'Poliéster',
    PONY_STYLE_CALFSKIN: 'Piel de ternero estilo pony',
    RUBBER: 'Caucho',
    SILK: 'Seda',
    SILVER: 'Plata',
    SILVER_PLATED: 'Chapado en plata',
    SPANDEX: 'Spandex',
    SPONGE: 'Esponja',
    STEEL: 'Acero',
    SUEDE: 'Gamuza',
    SYNTHETIC: 'Sintético',
    TWEED: 'Tweed',
    VEGAN_LEATHER: 'Cuero vegano',
    VELVET: 'Terciopelo',
    VINYL: 'Vinilo',
    VISCOSE: 'Viscosa',
    WHITE_GOLD: 'Oro blanco',
    WICKER: 'Mimbre',
    WOOL: 'Lana',
    YELLOW_GOLD: 'Oro amarillo',
  },
  en: {
    CASHMERE: 'Cashmere',
    CLOTH: 'Cloth',
    COTTON: 'Cotton',
    COTTON_ELASTHANE: 'Cotton - Elasthane',
    CRYSTAL: 'Crystal',
    DENIM_JEANS: 'Denim - Jeans',
    EXOTIC_LEATHERS: 'Exotic Leathers',
    FAUX_FUR: 'Faux Fur',
    FUR: 'Fur',
    GLASS: 'Glass',
    GLITTER: 'Glitter',
    GOLD_PLATED: 'Gold Plated',
    LACE: 'Lace',
    LEATHER: 'Leather',
    LINEN: 'Linen',
    LYCRA: 'Lycra',
    METAL: 'Metal',
    NOT_SPECIFIED: 'Not Specified',
    OTHER: 'Other',
    PATENT_LEATHER: 'Patent Leather',
    PEARL: 'Pearl',
    PINK_GOLD: 'Pink Gold',
    PLASTIC: 'Plastic',
    POLYAMIDE: 'Polyamide',
    POLYESTER: 'Polyester',
    PONY_STYLE_CALFSKIN: 'Pony-Style Calfskin',
    RUBBER: 'Rubber',
    SILK: 'Silk',
    SILVER: 'Silver',
    SILVER_PLATED: 'Silver Plated',
    SPANDEX: 'Spandex',
    SPONGE: 'Sponge',
    STEEL: 'Steel',
    SUEDE: 'Suede',
    SYNTHETIC: 'Synthetic',
    TWEED: 'Tweed',
    VEGAN_LEATHER: 'Vegan Leather',
    VELVET: 'Velvet',
    VINYL: 'Vinyl',
    VISCOSE: 'Viscose',
    WHITE_GOLD: 'White Gold',
    WICKER: 'Wicker',
    WOOL: 'Wool',
    YELLOW_GOLD: 'Yellow Gold',
  },
};

export const STRAP_MATERIALS = {
  es: [
    { value: 'STEEL', label: 'Acero' },
    { value: 'STEEL_AND_GOLD', label: 'Acero y oro' },
    { value: 'ALUMINUM', label: 'Aluminio' },
    { value: 'GOLD_PLATED', label: 'Bañado o chapado en oro' },
    { value: 'RUBBER', label: 'Caucho' },
    { value: 'CERAMIC', label: 'Cerámica' },
    { value: 'BRASS', label: 'Latón' },
    { value: 'YELLOW_GOLD', label: 'Oro amarillo' },
    { value: 'WHITE_GOLD', label: 'Oro blanco' },
    { value: 'RED_GOLD', label: 'Oro rojo' },
    { value: 'ROSE_GOLD', label: 'Oro rosa' },
    { value: 'LEATHER', label: 'Piel' },
    { value: 'ALLIGATOR_LEATHER', label: 'Piel de aligátor' },
    { value: 'OSTRICH_LEATHER', label: 'Piel de avestruz' },
    { value: 'LIZARD_LEATHER', label: 'Piel de lagarto' },
    { value: 'SNAKE_LEATHER', label: 'Piel de serpiente' },
    { value: 'SHARK_LEATHER', label: 'Piel de tiburon' },
    { value: 'COW_LEATHER', label: 'Piel de vaca' },
    { value: 'PLASTIC', label: 'Plástico' },
    { value: 'SILVER', label: 'Plata' },
    { value: 'PLATINUM', label: 'Platino' },
    { value: 'SATIN', label: 'Satén' },
    { value: 'SILICONE', label: 'Silicona' },
    { value: 'TEXTILE', label: 'Textil' },
    { value: 'TITANIUM', label: 'Titanio' },
    { value: 'UNSPECIFIED', label: 'Sin especificar' },
  ],
  en: [
    { value: 'ALUMINUM', label: 'Aluminum' },
    { value: 'BRASS', label: 'Brass' },
    { value: 'CERAMIC', label: 'Ceramic' },
    { value: 'COW_LEATHER', label: 'Cow Leather' },
    { value: 'GOLD_PLATED', label: 'Gold Plated' },
    { value: 'LEATHER', label: 'Leather' },
    { value: 'LIZARD_LEATHER', label: 'Lizard Leather' },
    { value: 'ALLIGATOR_LEATHER', label: 'Alligator Leather' },
    { value: 'OSTRICH_LEATHER', label: 'Ostrich Leather' },
    { value: 'PLASTIC', label: 'Plastic' },
    { value: 'PLATINUM', label: 'Platinum' },
    { value: 'SATIN', label: 'Satin' },
    { value: 'SAPPHIRE_CRYSTAL', label: 'Sapphire Crystal' },
    { value: 'SHARK_LEATHER', label: 'Shark Leather' },
    { value: 'SILICONE', label: 'Silicone' },
    { value: 'SILVER', label: 'Silver' },
    { value: 'SNAKE_LEATHER', label: 'Snake Leather' },
    { value: 'STEEL', label: 'Steel' },
    { value: 'STEEL_AND_GOLD', label: 'Steel and Gold' },
    { value: 'TEXTILE', label: 'Textile' },
    { value: 'TITANIUM', label: 'Titanium' },
    { value: 'RED_GOLD', label: 'Red Gold' },
    { value: 'ROSE_GOLD', label: 'Rose Gold' },
    { value: 'ROSE_GOLD_AND_STEEL', label: 'Rose Gold and Steel' },
    { value: 'WHITE_GOLD', label: 'White Gold' },
    { value: 'YELLOW_GOLD', label: 'Yellow Gold' },
    { value: 'UNSPECIFIED', label: 'Unspecified' },
  ],
};

export const BOX_MATERIALS = {
  es: [
    { value: 'STEEL', label: 'Acero' },
    { value: 'STEEL_AND_GOLD', label: 'Acero y oro' },
    { value: 'ALUMINUM', label: 'Aluminio' },
    { value: 'GOLD_PLATED', label: 'Bañado o chapado en oro' },
    { value: 'BRASS', label: 'Latón' },
    { value: 'BRONZE', label: 'Bronce' },
    { value: 'CARBON', label: 'Carbono' },
    { value: 'CERAMIC', label: 'Cerámica' },
    { value: 'SAPPHIRE_CRYSTAL', label: 'Cristal de zafiro' },
    { value: 'PALLADIUM', label: 'Paladio' },
    { value: 'PLASTIC', label: 'Plástico' },
    { value: 'PLATINUM', label: 'Platino' },
    { value: 'SILVER', label: 'Plata' },
    { value: 'TANTALUM', label: 'Tántalo' },
    { value: 'TITANIUM', label: 'Titanio' },
    { value: 'TUNGSTEN', label: 'Tungsteno' },
    { value: 'RED_GOLD', label: 'Oro rojo' },
    { value: 'ROSE_GOLD', label: 'Oro rosa' },
    { value: 'ROSE_GOLD_AND_STEEL', label: 'Oro rosa y acero' },
    { value: 'WHITE_GOLD', label: 'Oro blanco' },
    { value: 'WHITE_GOLD_AND_STEEL', label: 'Oro blanco y acero' },
    { value: 'YELLOW_GOLD', label: 'Oro amarillo' },
    { value: 'YELLOW_GOLD_AND_STEEL', label: 'Oro amarillo y acero' },
    { value: 'UNSPECIFIED', label: 'Sin especificar' },
  ],
  en: [
    { value: 'ALUMINUM', label: 'Aluminum' },
    { value: 'BRASS', label: 'Brass' },
    { value: 'BRONZE', label: 'Bronze' },
    { value: 'CARBON', label: 'Carbon' },
    { value: 'CERAMIC', label: 'Ceramic' },
    { value: 'SAPPHIRE_CRYSTAL', label: 'Sapphire Crystal' },
    { value: 'GOLD_PLATED', label: 'Gold Plated' },
    { value: 'PALLADIUM', label: 'Palladium' },
    { value: 'PLASTIC', label: 'Plastic' },
    { value: 'PLATINUM', label: 'Platinum' },
    { value: 'SILVER', label: 'Silver' },
    { value: 'STEEL', label: 'Steel' },
    { value: 'STEEL_AND_GOLD', label: 'Steel and Gold' },
    { value: 'TANTALUM', label: 'Tantalum' },
    { value: 'TITANIUM', label: 'Titanium' },
    { value: 'TUNGSTEN', label: 'Tungsten' },
    { value: 'RED_GOLD', label: 'Red Gold' },
    { value: 'ROSE_GOLD', label: 'Rose Gold' },
    { value: 'ROSE_GOLD_AND_STEEL', label: 'Rose Gold and Steel' },
    { value: 'WHITE_GOLD', label: 'White Gold' },
    { value: 'WHITE_GOLD_AND_STEEL', label: 'White Gold and Steel' },
    { value: 'YELLOW_GOLD', label: 'Yellow Gold' },
    { value: 'YELLOW_GOLD_AND_STEEL', label: 'Yellow Gold and Steel' },
    { value: 'UNSPECIFIED', label: 'Unspecified' },
  ],
};

export const STRAP_MATERIALS_LABELS: LabelsByLanguage = {
  es: {
    STEEL: 'Acero',
    STEEL_AND_GOLD: 'Acero y oro',
    ALUMINUM: 'Aluminio',
    GOLD_PLATED: 'Bañado o chapado en oro',
    RUBBER: 'Caucho',
    CERAMIC: 'Cerámica',
    BRASS: 'Latón',
    YELLOW_GOLD: 'Oro amarillo',
    WHITE_GOLD: 'Oro blanco',
    RED_GOLD: 'Oro rojo',
    ROSE_GOLD: 'Oro rosa',
    LEATHER: 'Piel',
    ALLIGATOR_LEATHER: 'Piel de aligátor',
    OSTRICH_LEATHER: 'Piel de avestruz',
    LIZARD_LEATHER: 'Piel de lagarto',
    SNAKE_LEATHER: 'Piel de serpiente',
    SHARK_LEATHER: 'Piel de tiburon',
    COW_LEATHER: 'Piel de vaca',
    PLASTIC: 'Plástico',
    SILVER: 'Plata',
    PLATINUM: 'Platino',
    SATIN: 'Satén',
    SILICONE: 'Silicona',
    TEXTILE: 'Textil',
    TITANIUM: 'Titanio',
    UNSPECIFIED: 'Sin especificar',
  },
  en: {
    ALUMINUM: 'Aluminum',
    BRASS: 'Brass',
    CERAMIC: 'Ceramic',
    COW_LEATHER: 'Cow Leather',
    GOLD_PLATED: 'Gold Plated',
    LEATHER: 'Leather',
    LIZARD_LEATHER: 'Lizard Leather',
    ALLIGATOR_LEATHER: 'Alligator Leather',
    OSTRICH_LEATHER: 'Ostrich Leather',
    PLASTIC: 'Plastic',
    PLATINUM: 'Platinum',
    SATIN: 'Satin',
    SAPPHIRE_CRYSTAL: 'Sapphire Crystal',
    SHARK_LEATHER: 'Shark Leather',
    SILICONE: 'Silicone',
    SILVER: 'Silver',
    SNAKE_LEATHER: 'Snake Leather',
    STEEL: 'Steel',
    STEEL_AND_GOLD: 'Steel and Gold',
    TEXTILE: 'Textile',
    TITANIUM: 'Titanium',
    RED_GOLD: 'Red Gold',
    ROSE_GOLD: 'Rose Gold',
    ROSE_GOLD_AND_STEEL: 'Rose Gold and Steel',
    WHITE_GOLD: 'White Gold',
    YELLOW_GOLD: 'Yellow Gold',
    UNSPECIFIED: 'Unspecified',
  },
};

export const BOX_MATERIALS_LABELS: LabelsByLanguage = {
  es: {
    STEEL: 'Acero',
    STEEL_AND_GOLD: 'Acero y oro',
    ALUMINUM: 'Aluminio',
    GOLD_PLATED: 'Bañado o chapado en oro',
    BRASS: 'Latón',
    BRONZE: 'Bronce',
    CARBON: 'Carbono',
    CERAMIC: 'Cerámica',
    SAPPHIRE_CRYSTAL: 'Cristal de zafiro',
    PALLADIUM: 'Paladio',
    PLASTIC: 'Plástico',
    PLATINUM: 'Platino',
    SILVER: 'Plata',
    TANTALUM: 'Tántalo',
    TITANIUM: 'Titanio',
    TUNGSTEN: 'Tungsteno',
    RED_GOLD: 'Oro rojo',
    ROSE_GOLD: 'Oro rosa',
    ROSE_GOLD_AND_STEEL: 'Oro rosa y acero',
    WHITE_GOLD: 'Oro blanco',
    WHITE_GOLD_AND_STEEL: 'Oro blanco y acero',
    YELLOW_GOLD: 'Oro amarillo',
    YELLOW_GOLD_AND_STEEL: 'Oro amarillo y acero',
    UNSPECIFIED: 'Sin especificar',
  },
  en: {
    ALUMINUM: 'Aluminum',
    BRASS: 'Brass',
    BRONZE: 'Bronze',
    CARBON: 'Carbon',
    CERAMIC: 'Ceramic',
    SAPPHIRE_CRYSTAL: 'Sapphire Crystal',
    GOLD_PLATED: 'Gold Plated',
    PALLADIUM: 'Palladium',
    PLASTIC: 'Plastic',
    PLATINUM: 'Platinum',
    SILVER: 'Silver',
    STEEL: 'Steel',
    STEEL_AND_GOLD: 'Steel and Gold',
    TANTALUM: 'Tantalum',
    TITANIUM: 'Titanium',
    TUNGSTEN: 'Tungsten',
    RED_GOLD: 'Red Gold',
    ROSE_GOLD: 'Rose Gold',
    ROSE_GOLD_AND_STEEL: 'Rose Gold and Steel',
    WHITE_GOLD: 'White Gold',
    WHITE_GOLD_AND_STEEL: 'White Gold and Steel',
    YELLOW_GOLD: 'Yellow Gold',
    YELLOW_GOLD_AND_STEEL: 'Yellow Gold and Steel',
    UNSPECIFIED: 'Unspecified',
  },
};

export const ARTICLE_SMELL = {
  es: [
    { value: 'TOBACCO', label: 'Tabaco' },
    { value: 'PERFUME', label: 'Perfume' },
    { value: 'HUMIDITY', label: 'Humedad' },
    { value: 'OTHER', label: 'Otro' },
    { value: 'NO_SMELL', label: 'Sin olor' },
  ],
  en: [
    { value: 'TOBACCO', label: 'Tobacco' },
    { value: 'PERFUME', label: 'Perfume' },
    { value: 'HUMIDITY', label: 'Humidity' },
    { value: 'OTHER', label: 'Other' },
    { value: 'NO_SMELL', label: 'No smell' },
  ],
};

export const WATCH_MOVEMENTS = {
  es: [
    { value: 'AUTOMATIC', label: 'Automático' },
    { value: 'QUARTZ', label: 'Cuarzo' },
    { value: 'MANUAL_WINDING', label: 'Cuerda manual' },
    { value: 'SMART_WATCH', label: 'Reloj inteligente' },
    { value: 'SOLAR', label: 'Solar' },
    { value: 'OTHER', label: 'Otro' },
  ],
  en: [
    { value: 'AUTOMATIC', label: 'Automatic' },
    { value: 'QUARTZ', label: 'Quartz' },
    { value: 'MANUAL_WINDING', label: 'Manual winding' },
    { value: 'SMART_WATCH', label: 'Smartwatch' },
    { value: 'SOLAR', label: 'Solar' },
    { value: 'OTHER', label: 'Other' },
  ],
};

export const WATCH_MOVEMENTS_LABELS: LabelsByLanguage = {
  es: {
    AUTOMATIC: 'Automático',
    QUARTZ: 'Cuarzo',
    MANUAL_WINDING: 'Cuerda manual',
    SMART_WATCH: 'Reloj inteligente',
    SOLAR: 'Solar',
    OTHER: 'Otro',
  },
  en: {
    AUTOMATIC: 'Automatic',
    QUARTZ: 'Quartz',
    MANUAL_WINDING: 'Manual winding',
    SMART_WATCH: 'Smartwatch',
    SOLAR: 'Solar',
    OTHER: 'Other',
  },
};

export const ART_TYPES = {
  es: [
    { value: 'OTHER', label: 'Otro' },
    { value: 'ANTIQUE', label: 'Antigüedad' },
    { value: 'CERAMIC', label: 'Cerámica' },
    { value: 'COLLECTIBLE', label: 'Coleccionable' },
    { value: 'DRAWING', label: 'Dibujo' },
    { value: 'FURNITURE', label: 'Mueble' },
    { value: 'GLASS_ART', label: 'Arte en vidrio' },
    { value: 'METAL_ART', label: 'Arte en metal' },
    { value: 'PAINTING', label: 'Pintura' },
    { value: 'SCULPTURE', label: 'Escultura' },
    { value: 'WOOD_ART', label: 'Arte en madera' },
  ],
  en: [
    { value: 'OTHER', label: 'Other' },
    { value: 'ANTIQUE', label: 'Antique' },
    { value: 'CERAMIC', label: 'Ceramic' },
    { value: 'COLLECTIBLE', label: 'Collectible' },
    { value: 'DRAWING', label: 'Drawing' },
    { value: 'FURNITURE', label: 'Furniture' },
    { value: 'GLASS_ART', label: 'Glass Art' },
    { value: 'METAL_ART', label: 'Metal Art' },
    { value: 'PAINTING', label: 'Painting' },
    { value: 'SCULPTURE', label: 'Sculpture' },
    { value: 'WOOD_ART', label: 'Wood Art' },
  ],
};

export const ART_TYPES_LABELS: LabelsByLanguage = {
  es: {
    OTHER: 'Otro',
    ANTIQUE: 'Antigüedad',
    CERAMIC: 'Cerámica',
    COLLECTIBLE: 'Coleccionable',
    DRAWING: 'Dibujo',
    FURNITURE: 'Mueble',
    GLASS_ART: 'Arte en vidrio',
    METAL_ART: 'Arte en metal',
    PAINTING: 'Pintura',
    SCULPTURE: 'Escultura',
    WOOD_ART: 'Arte en madera',
  },
  en: {
    OTHER: 'Other',
    ANTIQUE: 'Antique',
    CERAMIC: 'Ceramic',
    COLLECTIBLE: 'Collectible',
    DRAWING: 'Drawing',
    FURNITURE: 'Furniture',
    GLASS_ART: 'Glass Art',
    METAL_ART: 'Metal Art',
    PAINTING: 'Painting',
    SCULPTURE: 'Sculpture',
    WOOD_ART: 'Wood Art',
  },
};

export const ARTICLE_CATEGORIES_FILTER_LIST: Record<string, CategoryFilter[]> =
  {
    es: [
      { value: 'BAG', label: 'Bolso' },
      { value: 'JEWERLY', label: 'Joya' },
      { value: 'WATCH', label: 'Reloj' },
      { value: 'ART', label: 'Arte' },
    ],
    en: [
      { value: 'BAG', label: 'Bag' },
      { value: 'JEWERLY', label: 'Jewelry' },
      { value: 'WATCH', label: 'Watch' },
      { value: 'ART', label: 'Art' },
    ],
  };

export const ONLINE_STORE_ARTICLE_STATUS = {
  es: [
    { value: 'NOT_AVAILABLE', label: 'No disponible' },
    { value: 'AVAILABLE', label: 'Disponible' },
    { value: 'SOLD', label: 'Vendido' },
  ],
  en: [
    { value: 'NOT_AVAILABLE', label: 'Not available' },
    { value: 'AVAILABLE', label: 'Available' },
    { value: 'SOLD', label: 'Sold' },
  ],
};

export const OFFERS_OPTIONS: Record<Lang, OfferOption[]> = {
  es: [
    { value: 'ALL', label: 'Todos' },
    { value: 'WITH_ACCEPTED_OFFERS', label: 'Con ofertas aceptadas' },
    { value: 'WITH_PENDING_OFFERS', label: 'Con ofertas pendientes' },
    { value: 'WITHOUT_OFFERS', label: 'Sin ofertas' },
  ],
  en: [
    { value: 'ALL', label: 'All' },
    { value: 'WITH_ACCEPTED_OFFERS', label: 'With accepted offers' },
    { value: 'WITH_PENDING_OFFERS', label: 'With pending offers' },
    { value: 'WITHOUT_OFFERS', label: 'Without offers' },
  ],
};

export const ARTICLE_IMAGES_MAX = 10;
